export const getAllProducts = {
    GET_ALL_PRODUCTS_INIT : 'GET_ALL_PRODUCTS_INIT',
    GET_ALL_PRODUCTS_SUCCESS : 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAIL : 'GET_ALL_PRODUCTS_FAIL',
    GET_ALL_SEARCH_PRODUCTS : 'GET_ALL_SEARCH_PRODUCTS',
}

export const addProduct = {
    ADD_PRODUCT_SUCCESS:'ADD_PRODUCT_SUCCESS',
    INCREMENT_PRODUCT_SUCCESS:'INCREMENT_PRODUCT_SUCCESS',
    DECREMENT_PRODUCT_SUCCESS:'DECREMENT_PRODUCT_SUCCESS',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
}